### PR TITLE
fix: Reference based offing

### PR DESCRIPTION
**Pull request by superguigui**
This PR solves the special case when two handlers use two distinct but equal functions.

```js
function a () { console.log('a') }
function b () { console.log('a') }

var emitter = dush()
emitter.on('e', a)
emitter.on('e', b)
emitter.off('e', a) // removes both a and b handler
emitter.emit('e') // nothing happens
```

The problem was that handlers where compared by string in `on` function. If instead we use reference to the original handler function the comparaison will still work in our special case.

I also took the liberty of removing the useless check on a `.called` variable on the `once` handler wrapper.

This should fix issue #22

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Great! : )

**Comment by tunnckoCore** [comment]
Hm, why the heck CIs are missing in the checks ?! :D :D :D 

Don't worry, I'll handle all this shit ;d

**Comment by superguigui** [comment]
Oh man I don't know. I ran `npm audit fix`, maybe I shouldn't have 🤕...
Let me know If I can help !

**Comment by tunnckoCore** [comment]
Haha, no problem, no problem. We don't need fixes anyway, since we don't have deps, only devDeps which isn't a problem for a bit ;d

But anyway, i'll merge and update everything needed, my current repo boilerplate (e.g. as seen in [git-commits-since](https://github.com/tunnckoCoreLabs/git-commits-since) and [parse-commit-message](https://github.com/tunnckoCoreLabs/parse-commit-message)) and design is a lot more easier to work with and everything is automated.

**Comment by tunnckoCore** [comment]
@superguigui @sqal merged

Thanks, and sorry for the delays :man_facepalming: :laughing:

**Pull request merged**
